[project]
name = "agentic-ai-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "langgraph>=1.0.2",
    "notebook>=7.4.7",
    "python-dotenv>=1.2.1",
]
